import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";

const faqs = [
  {
    q: "What file formats can I upload?",
    a: "PDF, Word (.doc/.docx), and plain text — or just paste your CV text directly if you don't have a file handy.",
  },
  {
    q: "How accurate is the ATS score?",
    a: "It's generated by an AI model trained on how real ATS systems and recruiters actually screen resumes — not a generic word-count checker. Treat it as a strong signal, not a guarantee of any specific outcome.",
  },
  {
    q: "Is my CV data kept private?",
    a: "Your CV is only used to generate your analysis and is tied to your account, not shared or sold. You're always in control of your data.",
  },
  {
    q: "Do I need a different scan for every job?",
    a: "Run Job Match for each role you're serious about — it compares your CV against that specific description, so the gaps it flags are job-specific.",
  },
  {
    q: "Is there a free plan?",
    a: "Yes — your first CV scan doesn't need a card, and the core tools (analyze, match, interview prep) are free to use.",
  },
];

function FAQItem({ item, isOpen, onToggle }) {
  return (
    <div className="glass rounded-2xl overflow-hidden">
      <button
        onClick={onToggle}
        className="w-full flex items-center justify-between gap-4 px-6 py-5 text-left"
      >
        <span className="font-medium text-ink-100">{item.q}</span>
        <span
          className={`text-ink-500 shrink-0 transition-transform duration-300 ${isOpen ? "rotate-45" : ""}`}
        >
          +
        </span>
      </button>
      <AnimatePresence initial={false}>
        {isOpen && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.3, ease: "easeInOut" }}
            className="overflow-hidden"
          >
            <p className="px-6 pb-5 text-sm text-ink-300 leading-relaxed">{item.a}</p>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

export default function FAQ() {
  const [openIndex, setOpenIndex] = useState(0);

  return (
    <section id="faq" className="relative py-28">
      <div className="max-w-2xl mx-auto px-6">
        <h2 className="font-display text-3xl sm:text-4xl font-semibold text-ink-100 text-center mb-12">
          Questions people actually ask.
        </h2>
        <div className="space-y-3">
          {faqs.map((item, i) => (
            <FAQItem
              key={item.q}
              item={item}
              isOpen={openIndex === i}
              onToggle={() => setOpenIndex(openIndex === i ? -1 : i)}
            />
          ))}
        </div>
      </div>
    </section>
  );
}
